//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWarpHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad7")]
        public global::System.Windows.Forms.Keys savePosKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["savePosKey"]));
            }
            set {
                this["savePosKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad9")]
        public global::System.Windows.Forms.Keys loadPosKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["loadPosKey"]));
            }
            set {
                this["loadPosKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad4")]
        public global::System.Windows.Forms.Keys prevMapKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["prevMapKey"]));
            }
            set {
                this["prevMapKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad6")]
        public global::System.Windows.Forms.Keys nextMapKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["nextMapKey"]));
            }
            set {
                this["nextMapKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public global::System.Windows.Forms.Keys prevStationKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["prevStationKey"]));
            }
            set {
                this["prevStationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public global::System.Windows.Forms.Keys nextStationKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["nextStationKey"]));
            }
            set {
                this["nextStationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad8")]
        public global::System.Windows.Forms.Keys lockPosKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["lockPosKey"]));
            }
            set {
                this["lockPosKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad2")]
        public global::System.Windows.Forms.Keys teleportKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["teleportKey"]));
            }
            set {
                this["teleportKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad5")]
        public global::System.Windows.Forms.Keys autoKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["autoKey"]));
            }
            set {
                this["autoKey"] = value;
            }
        }
    }
}
